name: Win_FreeType

on:
  workflow_dispatch:
  push:
    branches:
    - freetype

jobs:
  build_Win_FreeType:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v1
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: build
      run: cmake --build build --config RelWithDebInfo
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ImGuiFontStudio_Msvc_x32
        path: build\RelWithDebInfo\ImGuiFontStudio_Msvc_x32.exe
